### ISSUE TITLE
`lune` no longer detected after updating to 0.4.0 / 0.4.1

### ISSUE THREAD

**Issue by hoontee** [ok-nick/setup-aftman#14]
https://github.com/Iron-Stag-Games/Lync/actions/runs/6242236709/job/16945829024

![image](https://github.com/ok-nick/setup-aftman/assets/5272529/399777a8-f47d-429e-933a-70110e7c9141)

**Comment by ok-nick** [comment]
Do the other installed tools run fine? Also try using the `test` branch with: `uses: ok-nick/setup-aftman@test`.

**Comment by hoontee** [comment]
`test` branch works.

https://github.com/Iron-Stag-Games/Lync/actions/runs/6244041640/job/16950366490

**Comment by ok-nick** [comment]
Released `v0.4.2`
